import { db } from "./index";
import { properties, buildings, residents, announcements } from "./schema";

async function seed() {
  console.log("Seeding database...");

  // Seed properties
  await db.insert(properties).values([
    {
      title: "آپارتمان لوکس در الهیه",
      description: "آپارتمان فوق‌العاده لوکس با نمای بی‌نظیر کوه، دارای سیستم هوشمند خانه، استخر و سالن ورزشی اختصاصی",
      propertyType: "apartment",
      listingType: "sale",
      status: "available",
      price: 85000000000,
      area: 320,
      bedrooms: 4,
      bathrooms: 3,
      floor: 12,
      totalFloors: 15,
      parking: true,
      elevator: true,
      storage: true,
      balcony: true,
      address: "تهران، الهیه، خیابان فرشته",
      neighborhood: "الهیه",
      city: "تهران",
      lat: 35.8147,
      lng: 51.4273,
      imageUrl: "https://images.pexels.com/photos/8135492/pexels-photo-8135492.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      hasCelebNeighbor: true,
      celebName: "علی کریمی",
      celebProfession: "ستاره فوتبال",
      yearBuilt: 1401,
      featured: true,
      viewCount: 1243,
      agentName: "امیر محمدی",
      agentPhone: "09121234567",
    },
    {
      title: "ویلای مدرن در نیاوران",
      description: "ویلای دوبلکس اختصاصی با باغ خصوصی، استخر آب‌گرم، سیستم هوشمند و پارکینگ ۴ خودرو",
      propertyType: "villa",
      listingType: "sale",
      status: "available",
      price: 150000000000,
      area: 600,
      bedrooms: 6,
      bathrooms: 4,
      floor: 1,
      totalFloors: 2,
      parking: true,
      elevator: false,
      storage: true,
      balcony: true,
      address: "تهران، نیاوران، خیابان دوستان",
      neighborhood: "نیاوران",
      city: "تهران",
      lat: 35.8147,
      lng: 51.4473,
      imageUrl: "https://images.pexels.com/photos/8135496/pexels-photo-8135496.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      hasCelebNeighbor: true,
      celebName: "مهناز افشار",
      celebProfession: "بازیگر سینما",
      yearBuilt: 1398,
      featured: true,
      viewCount: 2156,
      agentName: "سارا احمدی",
      agentPhone: "09131234567",
    },
    {
      title: "آپارتمان مدرن در زعفرانیه",
      description: "آپارتمان کاملاً بازسازی‌شده با دکوراسیون اروپایی، پنجره‌های دوجداره و سیستم گرمایش از کف",
      propertyType: "apartment",
      listingType: "sale",
      status: "available",
      price: 62000000000,
      area: 180,
      bedrooms: 3,
      bathrooms: 2,
      floor: 7,
      totalFloors: 10,
      parking: true,
      elevator: true,
      storage: false,
      balcony: true,
      address: "تهران، زعفرانیه، بلوار اندرزگو",
      neighborhood: "زعفرانیه",
      city: "تهران",
      lat: 35.7947,
      lng: 51.4173,
      imageUrl: "https://images.pexels.com/photos/7546323/pexels-photo-7546323.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      hasCelebNeighbor: false,
      yearBuilt: 1400,
      featured: true,
      viewCount: 987,
      agentName: "رضا کریمی",
      agentPhone: "09141234567",
    },
    {
      title: "پنت‌هاوس اختصاصی در جردن",
      description: "پنت‌هاوس منحصربه‌فرد با تراس ۲۰۰ متری، جکوزی روباز، نمای ۳۶۰ درجه تهران",
      propertyType: "apartment",
      listingType: "sale",
      status: "available",
      price: 230000000000,
      area: 450,
      bedrooms: 5,
      bathrooms: 4,
      floor: 20,
      totalFloors: 20,
      parking: true,
      elevator: true,
      storage: true,
      balcony: true,
      address: "تهران، جردن، خیابان آفریقا",
      neighborhood: "جردن",
      city: "تهران",
      lat: 35.7647,
      lng: 51.4073,
      imageUrl: "https://images.pexels.com/photos/8089172/pexels-photo-8089172.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      hasCelebNeighbor: true,
      celebName: "محمدرضا شجریان",
      celebProfession: "هنرمند برجسته",
      yearBuilt: 1402,
      featured: true,
      viewCount: 3421,
      agentName: "مهدی نوری",
      agentPhone: "09151234567",
    },
    {
      title: "آپارتمان رهن کامل در سعادت‌آباد",
      description: "آپارتمان نوساز آماده تحویل، کابینت‌های پروفیل آلومینیومی، سیستم تهویه مطبوع",
      propertyType: "apartment",
      listingType: "mortgage",
      status: "available",
      price: 8000000000,
      area: 130,
      bedrooms: 2,
      bathrooms: 1,
      floor: 3,
      totalFloors: 8,
      parking: true,
      elevator: true,
      storage: false,
      balcony: false,
      address: "تهران، سعادت‌آباد، بلوار دریا",
      neighborhood: "سعادت‌آباد",
      city: "تهران",
      lat: 35.7547,
      lng: 51.3873,
      imageUrl: "https://images.pexels.com/photos/12598504/pexels-photo-12598504.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      hasCelebNeighbor: false,
      yearBuilt: 1402,
      featured: false,
      viewCount: 654,
      agentName: "فاطمه موسوی",
      agentPhone: "09161234567",
    },
    {
      title: "آپارتمان اجاره‌ای در ونک",
      description: "آپارتمان تمیز و آفتابگیر در موقعیت عالی، نزدیک به متروی ونک و مراکز خرید",
      propertyType: "apartment",
      listingType: "rent",
      status: "available",
      price: 45000000,
      area: 95,
      bedrooms: 2,
      bathrooms: 1,
      floor: 5,
      totalFloors: 7,
      parking: false,
      elevator: true,
      storage: false,
      balcony: true,
      address: "تهران، ونک، خیابان ملاصدرا",
      neighborhood: "ونک",
      city: "تهران",
      lat: 35.7547,
      lng: 51.3973,
      imageUrl: "https://images.pexels.com/photos/8461634/pexels-photo-8461634.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      hasCelebNeighbor: false,
      yearBuilt: 1396,
      featured: false,
      viewCount: 432,
      agentName: "علی رضایی",
      agentPhone: "09171234567",
    },
  ]).onConflictDoNothing();

  // Seed buildings
  const [building1] = await db.insert(buildings).values([
    {
      name: "برج مسکونی ستاره",
      address: "تهران، الهیه، خیابان فرشته، پلاک ۱۲",
      totalUnits: 24,
      floors: 8,
      hasElevator: true,
      hasParking: true,
      monthlyCharge: 500000,
      adminName: "آقای احمدی",
      adminPhone: "09121111111",
    },
  ]).returning();

  if (building1) {
    await db.insert(residents).values([
      {
        buildingId: building1.id,
        name: "محمد رضایی",
        phone: "09121111110",
        unitNumber: "101",
        floor: 1,
        isPaid: true,
        debtAmount: 0,
        isActive: true,
      },
      {
        buildingId: building1.id,
        name: "سارا محمدی",
        phone: "09121111112",
        unitNumber: "201",
        floor: 2,
        isPaid: false,
        debtAmount: 1500000,
        isActive: true,
      },
      {
        buildingId: building1.id,
        name: "علی کریمی",
        phone: "09121111113",
        unitNumber: "301",
        floor: 3,
        isPaid: true,
        debtAmount: 0,
        isActive: true,
      },
    ]).onConflictDoNothing();

    await db.insert(announcements).values([
      {
        buildingId: building1.id,
        title: "جلسه هیئت‌مدیره",
        content: "جلسه ماهانه هیئت‌مدیره روز پنج‌شنبه ساعت ۱۸ در لابی ساختمان برگزار می‌شود",
        priority: "high",
      },
      {
        buildingId: building1.id,
        title: "نظافت عمومی ساختمان",
        content: "لطفاً روز جمعه اول ماه وسایل خود را از پارکینگ خارج نمایید",
        priority: "normal",
      },
    ]).onConflictDoNothing();
  }

  console.log("Seeding completed!");
}

seed().catch(console.error).finally(() => process.exit(0));
